install:
  - cmd: java -version
  - gcc -shared -o /tmp/testmodule.so -fPIC src/test/resources/testmodule.c


test_script:
  - mvn -Dtest=\!ModuleTest clean compile test

cache:
  - '%HOMEPATH%\.m2' 

build: off